export interface ThemeProps {
  fontSize: {
    font7: number;
    font8: number;
    font10: number;
    font12: number;
    font14: number;
    font16: number;
    font18: number;
    font20: number;
    font22: number;
    font24: number;
    font26: number;
    font28: number;
    font30: number;
    font32: number;
    font36: number;
  };
  colors: {
    white: string;
    black: string;
    primaryColor: string;
    primaryGreen: string;
    whiteShaded: string;
    teal: string;
    errorColor: string;
    fontColor: string;
    fontColor2: string;
    fontColor3: string;
    fontColor4: string;
    fontColor5: string;
    fontColor6: string;
    fontColor7: string;
    fontColor8: string;
    fontColor9: string;
    fontColor10: string;
    fontColor11: string;
    fontColor12: string;
    fontColor14: string;
    fontColor15: string;
    fontColor16: string;
    grayColor: string;
    lightGrayFont: string,
    lightGrayFont2: string,
    overlay_medium: string
    topBorderGradientMin: string;
    topBorderGradientMax: string;
    bottomBorderGradientMin: string;
    bottomBorderGradientMax: string;
    topErrorBorderGradientMin: string;
    topErrorBorderGradientMax: string;
    bottomErrorBorderGradientMin: string;
    placeholderTextColor: string;
    shadowColor: string;
    shadowColor2: string;
    shadowColor3: string;
    gradientColorMin: string;
    gradientColorMax: string;
    selectedViewColor: string;
    modalOverlay: string;
    gradientColorMin1: string;
    gradientColorMax1: string;
    gradientColorMax2: string;
    radialGradientMin: string;
    radialGradientMax: string;
    borderColor: string;
    blackOverlay: string;
    borderGreyColor: string;
    statusBarColor: string;
    greenGradientMin: string;
    greenGradientMax: string;
    borderColor1: string;
    fontColor13: string;
    buttonGradient: string;
    tealLightGradient: string;
    circleProgressCircle: string;
    yellow: string;
    progressGrey: string;
    yellowGradient1: string;
    yellowGradient2: string;
    yellowGradient3: string;
    yellowGradient4: string;
    blueGradientMin: string;
    blueGradientMax: string;
    lineColor: string;
    toastMinGradientColor: string;
    toastMinGradientRedColor: string;
    darkBlue: string;
    disabledButtonColor: string;
    purple: string;
    purple1: string
    lightPurple: string
    stripGradient1: string;
    stripGradient2: string;
    golden: string;
    lightGray: string;
    orangeGolden: string;
    skinColorMin: string;
    skinColorMax: string;
    red: string;
    green: string;
    darkGreen: string;
    darkGray: string;
    darkGray_primary: string;
    primaryBlue: string;
    primaryLightBlue: string;
    transparentBlue: string;
    primaryBackgroundColor: string;
    backgroundTealLight: string;
    background: string;
    borderBottomColor: string;
    primaryGrayColor: string;
    primaryGrayColor2: string;
    lightSkin: string;
    blueLight: string;
    transparentGreen: string;
    coachMarkBackground: string;
    transparent: string;
    transparentBeige: string;
    transparentRed: string;
  };
  opacity: {
    opacity0p15: number;
    opacity0p1: number;
    opacity0p2: number;
    opacity0p3: number;
    opacity0p4: number;
    opacity0p5: number;
    opacity0p6: number;
    opacity0p7: number;
    opacity0p8: number;
    opacity0p9: number;
    opacity1: number;
  };
  borderRadius: {
    radius1: number;
    radius2: number;
    radius3: number;
    radius4: number;
    radius5: number;
    radius6: number;
    radius8: number;
    radius10: number;
    radius12: number;
    radius14: number;
    radius16: number;
    radius18: number;
    radius20: number;
    radius28: number;
    radius32: number;
    radius35: number;
    radius40: number;
    radius50: number;
    radius58: number;
    radius64: number;
    radius78: number;
  };
  borderWidth: {
    borderWidth0p2: number,
    borderWidth0p4: number,
    borderWidth0p5: number,
    borderWidth0p6: number,
    borderWidth0p8: number,
    borderWidth1: number;
    borderWidth2: number;
    borderWidth3: number;
    borderWidth1p5: number;
    borderWidth10: number;
  };
}
